name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  Cypress-Run-Firefox:
    runs-on: macos-latest
    name: E2E on Firefox
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Укажите ту же версию Node.js, что и локально

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm ci

      # Шаг 4: Установка Firefox
      - name: Install Firefox
        run: brew install --cask firefox

      # Шаг 5: Запуск параллельных тестов через ваш скрипт
      - name: Run Cypress tests in parallel on Firefox
        run: npm run test:parallel:firefox

      # Шаг 6: Загрузка отчётов Mochawesome
      - name: Upload Mochawesome report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-firefox
          path: mochawesome-report-firefox/