name: Example Cypress GitHub Actions

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false

  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  docker-included:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge, firefox]
    container:
      image: cypress/included:latest
      options: --user 1001
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4
        with:
          # Если используется workflow_dispatch, то берем ветку из входных данных, иначе используем ветку из PR
          ref: ${{ github.event.inputs.branch || github.head_ref || github.ref }}

      # Устанавливаем зависимости
      - name: Install dependencies
        run: npm i

      # Запускаем Cypress тесты
      - uses: cypress-io/github-action@v6
        with:
          working-directory: examples/basic-mini
          browser: ${{ matrix.browser }}
        env:
          CYPRESS_INSTALL_BINARY: 0
