name: E2E Tests on Firefox

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  cypress-run-firefox:
    runs-on: ubuntu-latest
    name: E2E on Firefox
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Cypress
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: firefox
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests
        run: npx cypress run --browser firefox
