name: E2E TVOLEARN

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  Cypress-Run-Chrome:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Укажите нужную версию Node.js

      - name: Install dependencies
        run: npm ci  # Это установит зависимости, указанные в package-lock.json

      - name: Set up Cypress
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: chrome
          working-directory: ./
        continue-on-error: true 

      - name: Run Cypress tests
        run: npm run test:parallel:chrome
        working-directory: ./

      - name: Upload Mochawesome reports chrome
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-chrome
          path: ./mochawesome-report-chrome/