name: Cypress Tests

on: 
  push:
    branches:
      - main  # или любой другой бранч, на который вы хотите реагировать

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests in Electron
        uses: cypress-io/github-action@v6
        with:
          browser: electron
